# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
xcode_workspace: Example/CDAlertView.xcworkspace
xcode_sdk: iphonesimulator10.0
xcode_scheme: CDAlertView-Example
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod install --project-directory=Example
script:
- set -o pipefail
- xcodebuild -version
- pod lib lint
